### ISSUE TITLE
Issues with Building the Deployment Dev Container on a Remote Server

### ISSUE THREAD

**Issue by BiologyGeek** [microsoft/AzureTRE-Deployment#97]
Hello team,

As you are aware, setting up a Dev Container can be done in two ways: locally or remotely.

I must utilize the Remote Dev Container method. Here are the steps I've taken:

1. Connected to a virtual machine via SSH using VS Code on a remote server. The operating system of this virtual machine is 'Ubuntu Server 22.04 LTS'.
2. Installed Docker Engine on the Ubuntu Server following the official installation guide: https://docs.docker.com/engine/install/ubuntu/
3. Cloned the Azure TRE Deployment git repository on the Ubuntu Server.
4. Encountered an error while opening and building the development container. The log that appeared during the dev container build process in VSCode is as follows:

  ```bash
[11265 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681).
[11263 ms] Start: Resolving Remote
[11542 ms] Start: Run: /bin/sh 
[12582 ms] Start: Run in host: echo ~
[12879 ms] /home/devcontainer
[12879 ms] 
[12879 ms] Start: Run in host: id -un
[13229 ms] devcontainer
[13229 ms] 
[13230 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'devcontainer' || grep -E '^devcontainer|^[^:]*:[^:]*:devcontainer:' /etc/passwd || true)
[13530 ms] userEnvProbe: loginInteractiveShell (default)
[13531 ms] userEnvProbe: not found in cache
[13531 ms] userEnvProbe shell: /bin/bash
[14096 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[16122 ms] Setting up container for folder or workspace: /home/devcontainer/AzureTRE-Deployment
[16122 ms] Host authority: ssh-remote+7b22686f73744e616d65223a22417a7572655452452d446576636f6e7461696e65722d4f5648227d
[16123 ms] Start: Run: wsl -l -v
[16344 ms] Start: Run: wsl -d docker-desktop -e /bin/sh -c echo ~
[29291 ms] Start: Run: wsl -d docker-desktop -e /bin/sh -c cd '/root' && /bin/sh
[29455 ms] Start: Run in host: id -un
[30484 ms] root
[30484 ms] 
[30485 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[30490 ms] Start: Run in host: echo ~
[30491 ms] /root
[30492 ms] 
[30493 ms] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node'
[30498 ms] 
[30499 ms] 
[30499 ms] Exit code 1
[30499 ms] Start: Run in host: test -x '/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node'
[30501 ms] 
[30501 ms] 
[30501 ms] Exit code 1
[30502 ms] Start: Run in host: uname -s
[30503 ms] Linux
[30504 ms] 
[30504 ms] Start: Run in host: uname -m
[30506 ms] x86_64
[30506 ms] 
[30506 ms] Start: Run in host: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[30509 ms] PRETTY_NAME="Docker Desktop"
[30509 ms] 
[30512 ms] Start: Downloading VS Code Server
[30513 ms] 8b3775030ed1a69b13e4f4c628c612102e30a681 linux-x64 stable 
[125897 ms] Start: Installing VS Code Server
[125898 ms] Start: Run in host: mkdir -p /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681_1706449779767
[125904 ms] 
[125905 ms] 
[125905 ms] Start: Run in host: (dd iflag=fullblock bs=8192 count=11099 2>/dev/null; dd iflag=fullblock bs=7680 count=1 2>/dev/null) | tar --no-same-owner -x -C /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681_1706449779767
[126337 ms] 
[126337 ms] 
[126337 ms] Start: Run in host: mv -n /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681_1706449779767/* /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681 && rmdir /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681_1706449779767
[126339 ms] 
[126340 ms] 
[126340 ms] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.327.0.js'
[126344 ms] 
[126344 ms] 
[126351 ms] Host server: /bin/sh: /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node: not found
[126352 ms] userEnvProbe: loginInteractiveShell (default)
[126352 ms] userEnvProbe: not found in cache
[126352 ms] userEnvProbe shell: /bin/ash
[126370 ms] Error reading shell environment.
[126371 ms] Error: stream ended with:0 but wanted:9
        at l (c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:27:22149)
        at c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:27:22330
        at s (c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:30:5371)
        at Socket.<anonymous> (c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:30:5541)
        at Socket.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[126371 ms] Could not connect to WSL.
[126372 ms] stream is closed
[126373 ms] Start: Check Docker is running
[126374 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[126376 ms] Host server terminated (code: 127, signal: null).
[126974 ms] Server API version: 1.43
[126975 ms] Start: Run: docker volume ls -q
[127550 ms] Start: Run: docker volume create vscode
[128529 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/devcontainer/AzureTRE-Deployment --filter label=vsch.quality=stable
[129500 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --filter label=devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json
[130628 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment
[131358 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment
[132674 ms] Start: Run: /home/devcontainer/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node /home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/devcontainer/AzureTRE-Deployment --id-label devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --id-label devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --mount-workspace-git-root
[134248 ms] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 5.15.0-86-generic x64.
[134248 ms] Start: Run: git rev-parse --show-cdup
[134256 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --filter label=devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json
[134006 ms] Start: Run: /home/devcontainer/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node /home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-21a62060-e751-4739-bfd8-9c446ac5b1931706449652435 --workspace-folder /home/devcontainer/AzureTRE-Deployment --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --id-label devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --terminal-columns 121 --terminal-rows 23
[135349 ms] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 5.15.0-86-generic x64.
[135349 ms] Start: Run: docker buildx version
[135753 ms] github.com/docker/buildx v0.11.2 9872040
[135754 ms] 
[135754 ms] Start: Resolving Remote
[135757 ms] Start: Run: git rev-parse --show-cdup
[135830 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --filter label=devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json
[135847 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/python:dev-3.8-bullseye
[136196 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-devcontainer/container-features/0.54.1-1706449790063/Dockerfile-with-features -t vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33e5c8050 --target dev_containers_target_stage --build-arg DOCKER_GROUP_ID= --build-arg INTERACTIVE=true --build-arg OSS_REPO=microsoft/AzureTRE --build-arg OSS_VERSION=v0.16.0 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/devcontainer/AzureTRE-Deployment
[+] Building 122.7s (29/29) FINISHED                                                                      docker:default
 => [internal] load build definition from Dockerfile-with-features                                                  0.1s
 => => transferring dockerfile: 6.38kB                                                                              0.0s
 => [internal] load .dockerignore                                                                                   0.1s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/python:dev-3.8-bullseye                     0.3s
 => [internal] load build context                                                                                   0.0s
 => => transferring context: 6.97kB                                                                                 0.0s
 => [dev_container_auto_added_stage_label  1/23] FROM mcr.microsoft.com/vscode/devcontainers/python:dev-3.8-bulls  19.7s
 => => resolve mcr.microsoft.com/vscode/devcontainers/python:dev-3.8-bullseye@sha256:4ee7d2012e20ec7154a6b5915f496  0.0s
 => => sha256:4ee7d2012e20ec7154a6b5915f4968c7c29a012f7f9db64f1f0ece3df665ad73 1.61kB / 1.61kB                      0.0s
 => => sha256:7fb2cb54f768c84d15bf420090d0270750bb0914c5d536be86b1be35dd707bbe 21.25kB / 21.25kB                    0.0s
 => => sha256:24098c8d74fae9a314e70517566e785db7b39341cbc4bd63adf14c330728677c 54.60MB / 54.60MB                    1.6s
 => => sha256:3e4531da2f06f2911a5e67446c1ec507acb336afe7130741c6ed12ce442b730f 15.77MB / 15.77MB                    0.6s
 => => sha256:ce36c698b39f7199d0ab0ef7511c0fab456c51d5cc987d6ec799b7947c6cf263 3.74kB / 3.74kB                      0.0s
 => => sha256:e455cf41eadb2f19f014361006086cdc5b3de16f3d13bd1d586be63e66c7fc63 55.06MB / 55.06MB                    1.0s
 => => sha256:c6374b4ceb7a33a2609d9577d1f8cb5133e782949ab21f31086c1de775cb6843 196.90MB / 196.90MB                  5.8s
 => => extracting sha256:e455cf41eadb2f19f014361006086cdc5b3de16f3d13bd1d586be63e66c7fc63                           1.8s 
 => => sha256:f0057575cfb9dc2bd894fba68c9b4b9df1c22525a953b1b232f7da2cee8b95b5 6.29MB / 6.29MB                      1.4s 
 => => sha256:945f12884006c80ea795b0f78ec2a41bf71358ddb2af87c2aac1b2f0bbe84886 17.54MB / 17.54MB                    2.2s
 => => sha256:d865ca2b5ccaf5d317a13e772ce0a821ccdaacabecc412509b7e3e71e974a9ee 245B / 245B                          1.9s 
 => => sha256:b8c1b8f455e5de290bdb6b81e1d2173083baa70868b39aef4fc128d66b9cb93f 2.85MB / 2.85MB                      2.3s 
 => => sha256:6590b87c493231e72b83ce913a190681add41495c2356e7627de8983527463c7 14.21MB / 14.21MB                    2.9s
 => => sha256:678fd6acbe4117122053415b6ac79bb9f65712bd06e3858dd22998eedf53686c 5.01MB / 5.01MB                      2.6s
 => => sha256:7fb2c6f09fc45b0b3fa3b865a8c46b462cd09e8a7cc934ac3ff901b3d4513975 405B / 405B                          2.9s
 => => extracting sha256:3e4531da2f06f2911a5e67446c1ec507acb336afe7130741c6ed12ce442b730f                           0.3s
 => => sha256:3a2def7b840fe0490235c201522e13a7cc47231ce6ef66c33cb7ef8d283c0f42 224B / 224B                          3.1s
 => => sha256:03a85d64957f40f832acbf6ae55c2828fab0e033f0f5eb0d10eec263be03d633 135B / 135B                          3.1s
 => => sha256:4d6fa48b12ed828cea184243640d2117a9bffa552e74235af8de0f9e48d56c8c 234B / 234B                          3.3s
 => => sha256:52d63e4f6aa24b9c2c7218a34b04042ad96353a18087503589c571c992d05cfd 48.91MB / 48.91MB                    4.6s
 => => extracting sha256:24098c8d74fae9a314e70517566e785db7b39341cbc4bd63adf14c330728677c                           1.9s
 => => sha256:50f9b4c44266cd3eae1a476e562d18ea84c6a30dc62aa3e495a91ca777e13f80 63.70MB / 63.70MB                    5.2s
 => => sha256:ce0f9d8bf41b5575dd4b8093b6d7c45ac0673f2e5aa6fb38f9de9ae82e09bd89 2.26MB / 2.26MB                      5.2s
 => => sha256:b0eb0a73c82f71085dc731ccfaba4eb61f1e85b319a44bd32ddef1560afbfd21 57.06MB / 57.06MB                    6.8s
 => => extracting sha256:c6374b4ceb7a33a2609d9577d1f8cb5133e782949ab21f31086c1de775cb6843                           5.2s
 => => extracting sha256:f0057575cfb9dc2bd894fba68c9b4b9df1c22525a953b1b232f7da2cee8b95b5                           0.2s
 => => extracting sha256:945f12884006c80ea795b0f78ec2a41bf71358ddb2af87c2aac1b2f0bbe84886                           0.5s
 => => extracting sha256:d865ca2b5ccaf5d317a13e772ce0a821ccdaacabecc412509b7e3e71e974a9ee                           0.0s
 => => extracting sha256:b8c1b8f455e5de290bdb6b81e1d2173083baa70868b39aef4fc128d66b9cb93f                           0.2s
 => => extracting sha256:6590b87c493231e72b83ce913a190681add41495c2356e7627de8983527463c7                           0.1s
 => => extracting sha256:678fd6acbe4117122053415b6ac79bb9f65712bd06e3858dd22998eedf53686c                           0.3s
 => => extracting sha256:7fb2c6f09fc45b0b3fa3b865a8c46b462cd09e8a7cc934ac3ff901b3d4513975                           0.0s
 => => extracting sha256:03a85d64957f40f832acbf6ae55c2828fab0e033f0f5eb0d10eec263be03d633                           0.0s
 => => extracting sha256:3a2def7b840fe0490235c201522e13a7cc47231ce6ef66c33cb7ef8d283c0f42                           0.0s
 => => extracting sha256:4d6fa48b12ed828cea184243640d2117a9bffa552e74235af8de0f9e48d56c8c                           0.0s
 => => extracting sha256:52d63e4f6aa24b9c2c7218a34b04042ad96353a18087503589c571c992d05cfd                           2.0s
 => => extracting sha256:50f9b4c44266cd3eae1a476e562d18ea84c6a30dc62aa3e495a91ca777e13f80                           1.2s
 => => extracting sha256:ce0f9d8bf41b5575dd4b8093b6d7c45ac0673f2e5aa6fb38f9de9ae82e09bd89                           0.1s
 => => extracting sha256:b0eb0a73c82f71085dc731ccfaba4eb61f1e85b319a44bd32ddef1560afbfd21                           2.8s
 => [dev_container_auto_added_stage_label  2/23] RUN usermod --uid 1000 vscode                                      4.5s
 => [dev_container_auto_added_stage_label  3/23] RUN su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh &&   4.2s
 => [dev_container_auto_added_stage_label  4/23] COPY .devcontainer/scripts/terraform.sh /tmp/                      0.0s
 => [dev_container_auto_added_stage_label  5/23] RUN bash /tmp/terraform.sh "1.4.5" /usr/bin                        1.2s
 => [dev_container_auto_added_stage_label  6/23] COPY .devcontainer/scripts/docker-client.sh /tmp/                  0.0s
 => [dev_container_auto_added_stage_label  7/23] RUN /tmp/docker-client.sh vscode                                   0.3s
 => [dev_container_auto_added_stage_label  8/23] RUN apt-get update && apt-get install -y ca-certificates curl gn  16.0s
 => [dev_container_auto_added_stage_label  9/23] RUN if [ "true" = "true" ]; then     apt-get update && apt-get i  12.2s
 => [dev_container_auto_added_stage_label 10/23] COPY .devcontainer/scripts/porter-v1.sh /tmp/                      0.0s
 => [dev_container_auto_added_stage_label 11/23] RUN export PORTER_VERSION=v1.0.11     PORTER_TERRAFORM_MIXIN_VERS  9.4s
 => [dev_container_auto_added_stage_label 12/23] COPY .devcontainer/scripts/azure-cli.sh /tmp/                      0.1s
 => [dev_container_auto_added_stage_label 13/23] RUN export AZURE_CLI_VERSION=2.50.0-1~bullseye     && /tmp/azure  18.0s
 => [dev_container_auto_added_stage_label 14/23] RUN curl -L --fail -o /usr/local/bin/yq "https://github.com/mikef  1.3s
 => [dev_container_auto_added_stage_label 15/23] RUN npm install -g pajv@1.2.0                                     14.2s
 => [dev_container_auto_added_stage_label 16/23] RUN if [ "true" = "false" ]; then apt-get update && apt-get insta  0.5s
 => [dev_container_auto_added_stage_label 17/23] RUN echo "export HISTFILE=$HOME/commandhistory/.bash_history" >>   0.3s
 => [dev_container_auto_added_stage_label 18/23] COPY ./.devcontainer/scripts/gh.sh /tmp/                           0.1s
 => [dev_container_auto_added_stage_label 19/23] RUN if [ "true" = "true" ]; then /tmp/gh.sh; fi                    1.4s
 => [dev_container_auto_added_stage_label 20/23] COPY .devcontainer/scripts/install-azure-tre-oss.sh .devcontainer  0.1s
 => [dev_container_auto_added_stage_label 21/23] RUN oss_repo_in_json=$(grep -oP '(?<="OSS_REPO": ")[^"]*' /tmp/de  1.8s
 => [dev_container_auto_added_stage_label 22/23] WORKDIR //home/vscode/AzureTRE/cli                                 0.1s
 => [dev_container_auto_added_stage_label 23/23] RUN make install-cli && echo -e "\n# Set up tre completion\nsour  11.3s
 => preparing layers for inline cache                                                                               5.5s
 => exporting to image                                                                                              0.0s
 => => exporting layers                                                                                             0.0s
 => => writing image sha256:4b5f4199a2d396512537bfdd4adc5c6f3ca7af4866ac6124251d1aea987241a8                        0.0s
 => => naming to docker.io/library/vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f  0.0s
[259093 ms] Start: Run: docker inspect --type image vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33e5c8050
[259113 ms] Start: Run: docker build -f /tmp/devcontainercli-devcontainer/updateUID.Dockerfile-0.54.1 -t vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33e5c8050-uid --build-arg BASE_IMAGE=vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33e5c8050 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=vscode /tmp/devcontainercli-devcontainer/empty-folder
[+] Building 0.9s (6/6) FINISHED                                                                          docker:default
 => [internal] load build definition from updateUID.Dockerfile-0.54.1                                               0.0s
 => => transferring dockerfile: 1.36kB                                                                              0.0s
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load metadata for docker.io/library/vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc9  0.0s
 => [1/2] FROM docker.io/library/vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33  0.4s
 => [2/2] RUN eval $(sed -n "s/vscode:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDE  0.3s
 => exporting to image                                                                                              0.1s
 => => exporting layers                                                                                             0.0s
 => => writing image sha256:cddadd87c796a23366e187879d8a0da69aa4ab418a9afb2a73c11d313732a409                        0.0s
 => => naming to docker.io/library/vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f  0.0s
[260138 ms] Start: Run: docker -v
[260153 ms] Start: Run: docker events --format {{json .}} --filter event=start
[260156 ms] Start: Starting container
[260156 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/devcontainer/AzureTRE-Deployment,target=/workspaces/AzureTRE-Deployment --mount type=volume,source=tre-bashhistory,target=/home/vscode/commandhistory --mount type=bind,source=/home/devcontainer/.azure,target=/home/vscode/.azure --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --mount type=bind,source=/home/devcontainer/.config,target=/home/vscode/.config --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment -l devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json -e DOCKER_BUILDKIT=1 --network host --entrypoint /bin/sh vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33e5c8050-uid -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/devcontainer/.azure.
See 'docker run --help'.
[260172 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --filter label=devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json
[259460 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/devcontainer/AzureTRE-Deployment,target=/workspaces/AzureTRE-Deployment --mount type=volume,source=tre-bashhistory,target=/home/vscode/commandhistory --mount type=bind,source=/home/devcontainer/.azure,target=/home/vscode/.azure --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --mount type=bind,source=/home/devcontainer/.config,target=/home/vscode/.config --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment -l devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json -e DOCKER_BUILDKIT=1 --network host --entrypoint /bin/sh vsc-azuretre-deployment-5bc7df7de06830f6f376e5d9515a3c233d84dc93bcafc7322a9e26f33e5c8050-uid -c echo Container started
[259460 ms] trap "exit 0" 15
[259460 ms] exec "$@"
[259460 ms] while sleep 1 & wait $!; do :; done -
[259461 ms]     at J$ (/home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1253)
[259461 ms]     at $J (/home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:997)
[259461 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[259461 ms]     at async tAA (/home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[259461 ms]     at async CC (/home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[259461 ms]     at async NeA (/home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[259461 ms]     at async MeA (/home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[259461 ms] Exit code 1
[259466 ms] Command failed: /home/devcontainer/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node /home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-21a62060-e751-4739-bfd8-9c446ac5b1931706449652435 --workspace-folder /home/devcontainer/AzureTRE-Deployment --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --id-label devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --terminal-columns 121 --terminal-rows 23
[259466 ms] Exit code 1
  ```

During the dev container build process, the following part of the log turned red:
  ```bash
[126351 ms] Host server: /bin/sh: /root/.vscode-remote-containers/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node: not found
  ```
  ```bash
[126371 ms] Error: stream ended with:0 but wanted:9
        at l (c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:27:22149)
        at c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:27:22330
        at s (c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:30:5371)
        at Socket.<anonymous> (c:\Users\Multiomics\.vscode\extensions\ms-vscode-remote.remote-containers-0.327.0\dist\extension\extension.js:30:5541)
        at Socket.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  ```
![During the dev container build process the following part of the log turned red 1](https://github.com/microsoft/AzureTRE-Deployment/assets/157970993/a4892366-3fe2-4751-b013-0b8c2808b2cd)

  ```bash
[259466 ms] Command failed: /home/devcontainer/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node /home/devcontainer/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-21a62060-e751-4739-bfd8-9c446ac5b1931706449652435 --workspace-folder /home/devcontainer/AzureTRE-Deployment --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/devcontainer/AzureTRE-Deployment --id-label devcontainer.config_file=/home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/devcontainer/AzureTRE-Deployment/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --terminal-columns 121 --terminal-rows 23
  ```
![During the dev container build process the following part of the log turned red 2](https://github.com/microsoft/AzureTRE-Deployment/assets/157970993/adebde0f-0334-48fb-bb92-f25dd88c9219)

Could you kindly share your insights to help resolve this issue, please?

**Comment by marrobi** [comment]
Hi @BiologyGeek this looks like a VSCode or Docker configuration issue. Limited as to what help we can provide. A couple of links after a search show it could be a corrupt vscode-server install - https://stackoverflow.com/questions/62437983/vscode-remote-server-sh-not-finding-node-in-wsl-docker-desktop

If you can't resolve, suggest posting an issue here - https://github.com/microsoft/vscode-remote-release . 

Do let us know how you get on.
